import type { Metadata } from 'next'
import './globals.css';  
import localFont from '@next/font/local'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const gellix = localFont({
  src: [
    {
      path: '../public/fonts/Gellix-Regular.ttf',
      weight: '400'
    }
  ],
  variable: '--font-gellix'
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={ `font-Gellix min-h-screen`}>
      <body className="flex flex-col min-h-screen bg-[#f7f7f7]">
        {/* <Navbar /> */}
        <div className="flex-1">
          {children}
        </div>
        {/* <Footer /> */}
      </body>
    </html>
  )
}
