import type { Metadata } from 'next'
import './globals.css';  

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={ `font-Gellix min-h-screen`}>
      <body className="flex flex-col min-h-screen bg-[#f7f7f7]">
        <div className="flex-1">
          {children}
        </div> 
      </body>
    </html>
  )
}
