import type { Metadata } from 'next'
import './globals.css';  
import Navbar from "./components/navbar";
import Footer from "./components/footer";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="min-h-screen">
      <body className="flex flex-col min-h-screen bg-[#f7f7f7]">
        {/* <Navbar /> */}
        <div className="flex-1">
          {children}
        </div>
        {/* <Footer /> */}
      </body>
    </html>
  )
}
